events {
	worker_connections 1024;
}

pid logs/balanceo.pid;

http {

upstream 3sitios {
    server localhost:81;
    server localhost:82;
    server localhost:83;
    }
    
	server {
		listen 80;



	location / {
        proxy_pass http://3sitios;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
		}
	}
}
